google_project_id       = "daring-acumen-315900"
google_bucket_name      = "fuchicorp-aiperi-s"
deployment_environment  = "dev"
deployment_name         = "hello-world"
credentials             = "fuchicopr-service-account.json"
